services:
  pokemon-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokemon-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production   
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
